### ISSUE TITLE
Failed to Load on Android Tablet

### ISSUE THREAD

**Issue by JuergenKaettnis** [johackim/obsidian-writing#1]
I downloaded the plugin via BRAT. When enabling, I get the message "Failed to load plugin." I am using Samsung Tablet S4. All software up to date. Is the plugin not for Android? Or some other issues?

**Comment by johackim** [comment]
Hello @JuergenKaettnis, thanks for your issue. The plugin is now on the official store (version 0.4.0), do you still have this problem?

**Comment by seanzhang9999** [comment]
I am also meet this problem，an android mobile phone with 6 inches screen, download from official store with 0.4.0, and report failed to load plugin writing,

**Comment by johackim** [comment]
The plugin doesn't support Android or iOS for the moment, sorry 😉
