### ISSUE TITLE
Plugin ID mismatch

### ISSUE THREAD

**Issue by Foxhunter-de** [johackim/obsidian-writing#3]
Hi,

when i try to install the plugin i get the error message "Plugin ID mismatch". I'm using Obsidian 1.1.9. Since there are no more details, i can't tell you anymore, sorry.

**Comment by johackim** [comment]
Hello @pce-Consulting, thank you for this issue. I updated the plugin (version 0.4.0) and it should work fine now. :)

**Comment by Foxhunter-de** [comment]
Works like a charm, thank you for the fast response & fix! :)
